version: '3'
services:

    sampledjango:
        build: ./sampledjango
        image: sample_django:latest
        ports:
        - 80:8000
        depends_on:
        - db

    db:
        image: mysql:5.7
        ports:
        - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sampledjango
          MYSQL_USER: username
          MYSQL_PASSWORD: password
        volumes:
        - /tmp/docker_volume/mysql:/var/lib/mysql
